// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1/transaction.proto

package log_v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/proto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TransactionRequest struct {
	Amount               *BigDecimal `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66979fffb2953f82, []int{0}
}
func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (m *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(m, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetAmount() *BigDecimal {
	if m != nil {
		return m.Amount
	}
	return nil
}

type TransactionResponse struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66979fffb2953f82, []int{1}
}
func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResponse.Unmarshal(m, b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
}
func (m *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(m, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResponse.Size(m)
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func (m *TransactionResponse) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type Transaction struct {
	SenderId             *UUID       `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId           *UUID       `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Amount               *BigDecimal `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt            *time.Time  `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_66979fffb2953f82, []int{2}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetSenderId() *UUID {
	if m != nil {
		return m.SenderId
	}
	return nil
}

func (m *Transaction) GetReceiverId() *UUID {
	if m != nil {
		return m.ReceiverId
	}
	return nil
}

func (m *Transaction) GetAmount() *BigDecimal {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Transaction) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type UUID struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}
func (*UUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_66979fffb2953f82, []int{3}
}
func (m *UUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUID.Unmarshal(m, b)
}
func (m *UUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUID.Marshal(b, m, deterministic)
}
func (m *UUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUID.Merge(m, src)
}
func (m *UUID) XXX_Size() int {
	return xxx_messageInfo_UUID.Size(m)
}
func (m *UUID) XXX_DiscardUnknown() {
	xxx_messageInfo_UUID.DiscardUnknown(m)
}

var xxx_messageInfo_UUID proto.InternalMessageInfo

func (m *UUID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type BigDecimal struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigDecimal) Reset()         { *m = BigDecimal{} }
func (m *BigDecimal) String() string { return proto.CompactTextString(m) }
func (*BigDecimal) ProtoMessage()    {}
func (*BigDecimal) Descriptor() ([]byte, []int) {
	return fileDescriptor_66979fffb2953f82, []int{4}
}
func (m *BigDecimal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigDecimal.Unmarshal(m, b)
}
func (m *BigDecimal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigDecimal.Marshal(b, m, deterministic)
}
func (m *BigDecimal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigDecimal.Merge(m, src)
}
func (m *BigDecimal) XXX_Size() int {
	return xxx_messageInfo_BigDecimal.Size(m)
}
func (m *BigDecimal) XXX_DiscardUnknown() {
	xxx_messageInfo_BigDecimal.DiscardUnknown(m)
}

var xxx_messageInfo_BigDecimal proto.InternalMessageInfo

func (m *BigDecimal) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*TransactionRequest)(nil), "log.v1.TransactionRequest")
	proto.RegisterType((*TransactionResponse)(nil), "log.v1.TransactionResponse")
	proto.RegisterType((*Transaction)(nil), "log.v1.Transaction")
	proto.RegisterType((*UUID)(nil), "log.v1.UUID")
	proto.RegisterType((*BigDecimal)(nil), "log.v1.BigDecimal")
}

func init() { proto.RegisterFile("api/v1/transaction.proto", fileDescriptor_66979fffb2953f82) }

var fileDescriptor_66979fffb2953f82 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xad, 0xce, 0xe2, 0x5e, 0xbd, 0x98, 0xed, 0x30, 0xaa, 0x30, 0xc9, 0x49, 0x05, 0x53,
	0x36, 0xf1, 0xac, 0xce, 0x5d, 0x0a, 0xc3, 0x43, 0xd9, 0xc0, 0xdb, 0xc8, 0xda, 0x67, 0x08, 0xb4,
	0x4d, 0x6d, 0xd3, 0xfe, 0x1d, 0xfe, 0x71, 0xde, 0xfd, 0x57, 0x64, 0x4d, 0xcb, 0x2a, 0x14, 0xbc,
	0x35, 0xfd, 0x7e, 0xf9, 0xf2, 0xbe, 0xef, 0xc1, 0x84, 0x67, 0xd2, 0xab, 0x66, 0x9e, 0xce, 0x79,
	0x5a, 0xf0, 0x50, 0x4b, 0x95, 0xb2, 0x2c, 0x57, 0x5a, 0x11, 0x3b, 0x56, 0x82, 0x55, 0x33, 0x77,
	0x2c, 0x94, 0x50, 0xf5, 0x2f, 0x6f, 0xff, 0x65, 0x54, 0x77, 0x2a, 0x94, 0x12, 0x31, 0x7a, 0xf5,
	0x69, 0x57, 0x7e, 0x78, 0x5a, 0x26, 0x58, 0x68, 0x9e, 0x64, 0x06, 0xa0, 0xcf, 0x40, 0xd6, 0x07,
	0xcf, 0x00, 0x3f, 0x4b, 0x2c, 0x34, 0xb9, 0x03, 0x9b, 0x27, 0xaa, 0x4c, 0xf5, 0xc4, 0xba, 0xb6,
	0x6e, 0x9c, 0x39, 0x61, 0xe6, 0x15, 0xb6, 0x90, 0x62, 0x89, 0xa1, 0x4c, 0x78, 0x1c, 0x34, 0x04,
	0x5d, 0xc1, 0xe8, 0x8f, 0x43, 0x91, 0xa9, 0xb4, 0x40, 0xf2, 0x08, 0x4e, 0x67, 0xd8, 0xc6, 0x67,
	0xd4, 0xfa, 0x74, 0x6f, 0x74, 0x39, 0xfa, 0x6d, 0x81, 0xd3, 0x11, 0xc9, 0x2d, 0x0c, 0x0b, 0x4c,
	0x23, 0xcc, 0xb7, 0x32, 0x6a, 0x4c, 0xce, 0x5b, 0x93, 0xcd, 0xc6, 0x5f, 0x06, 0x67, 0x46, 0xf6,
	0x23, 0x72, 0x0f, 0x4e, 0x8e, 0x21, 0xca, 0xca, 0xc0, 0xc7, 0x3d, 0x30, 0xb4, 0x80, 0x1f, 0x75,
	0x32, 0x9e, 0xfc, 0x97, 0x91, 0x3c, 0x01, 0x84, 0x39, 0x72, 0x8d, 0xd1, 0x96, 0xeb, 0xc9, 0xa0,
	0xe6, 0x5d, 0x66, 0xba, 0x65, 0x6d, 0xb7, 0x6c, 0xdd, 0x76, 0xbb, 0x18, 0x7c, 0xfd, 0x4c, 0xad,
	0x60, 0xd8, 0xdc, 0x79, 0xd1, 0xf4, 0x0a, 0x06, 0xfb, 0x01, 0xc8, 0x18, 0x4e, 0x2b, 0x1e, 0x97,
	0x58, 0x47, 0x19, 0x06, 0xe6, 0x40, 0x29, 0xc0, 0xe1, 0xd1, 0x7e, 0x66, 0xfe, 0x0e, 0xf6, 0x0a,
	0x23, 0x81, 0x39, 0x79, 0x83, 0x8b, 0xd7, 0xda, 0xb8, 0xdb, 0x93, 0xdb, 0xd7, 0xac, 0xd9, 0xa6,
	0x7b, 0xd9, 0xab, 0x99, 0x3d, 0xd1, 0xa3, 0x9d, 0x5d, 0x07, 0x78, 0xf8, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0x5e, 0x47, 0xc6, 0x57, 0x64, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LedgerClient is the client API for Ledger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LedgerClient interface {
	CreateTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
}

type ledgerClient struct {
	cc *grpc.ClientConn
}

func NewLedgerClient(cc *grpc.ClientConn) LedgerClient {
	return &ledgerClient{cc}
}

func (c *ledgerClient) CreateTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, "/log.v1.Ledger/CreateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServer is the server API for Ledger service.
type LedgerServer interface {
	CreateTransaction(context.Context, *TransactionRequest) (*TransactionResponse, error)
}

// UnimplementedLedgerServer can be embedded to have forward compatible implementations.
type UnimplementedLedgerServer struct {
}

func (*UnimplementedLedgerServer) CreateTransaction(ctx context.Context, req *TransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}

func RegisterLedgerServer(s *grpc.Server, srv LedgerServer) {
	s.RegisterService(&_Ledger_serviceDesc, srv)
}

func _Ledger_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log.v1.Ledger/CreateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServer).CreateTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ledger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "log.v1.Ledger",
	HandlerType: (*LedgerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTransaction",
			Handler:    _Ledger_CreateTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/transaction.proto",
}
